var masterlist = [
    "whoop ass!",
    "bank on!",
    "hold your fire!",
    "props-up!",
    "balls about!",
    "lily-livered!",
    "fall in with!",
    "asleep at the wheel!",
    "Green Thumb!",
    "no more Mr. Nice Guy!",
    "On the Ropes!",
    "bow out!",
    "fit into!",
    "i'm livin' the dream!",
    "a cloud of uncertainty!",
    "hold up!",
    "phase out!",
    "and then some!",
    "get the ball rolling!!",
    "every man for himself!!",
    "the sky is the limit!!!",
    "read the tea-leaves!",
    "crank out!",
    "Sad sack!",
    "have truck with!",
    "blow over!",
    "brag on!",
    "what a load of magumba....!",
    "front runner!",
    "a bridge too far!",
    "clutter up!",
    "sleep camel!",
    "build up!",
    "sooner or later!",
    "food baby!",
    "pick up!",
    "douchebagerry!",
    "have in tow!",
    "under the table!",
    "by hook or by crook!",
    "hold this one!",
    "round out!",
    "put up!",
    "pro forma!",
    "dead cat bounce!",
    "doss down!",
    "Run around after!",
    "all piss and wind like a barber cat!",
    "Na-na na-na boo-boo!",
    "Yankee dime!",
    "turn up for the book!",
    "give something a try!",
    "pencil-neck!",
    "every man jack!",
    "fashion police!",
];

function guessRandomWord() {
    let randomNum = Math.floor(Math.random() * 55); //have 55 world in the list
    //console.log("Random number : " + randomNum);
    return masterlist[randomNum];
}

module.exports = { guessRandomWord: guessRandomWord };